version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: foxtrot
      POSTGRES_PASSWORD: foxtrot
      POSTGRES_DB: light_engine_foxtrot
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U foxtrot"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  pgdata:
