/**
 * DATABASE SCHEMA MIGRATION - Crop Recommendation System
 * 
 * Adds tables for tracking:
 * - Recommendation history (what system suggested)
 * - Planting decisions (what grower actually chose)
 * - Success metrics (acceptance rate, override patterns)
 * 
 * Run with: sqlite3 data/lightengine.db < migrations/001_crop_recommendations.sql
 */

-- Track all crop recommendations generated by system
CREATE TABLE IF NOT EXISTS planting_recommendations (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  farm_id TEXT NOT NULL,
  group_id TEXT NOT NULL,
  tray_id TEXT,
  current_crop TEXT,
  recommended_crop TEXT NOT NULL,
  recommended_date DATE NOT NULL,
  confidence REAL,
  
  -- Score breakdown
  score_nutrient REAL,
  score_demand REAL,
  score_stagger REAL,
  score_light REAL,
  score_vpd REAL,
  score_overall REAL,
  
  -- Zone conditions at time of recommendation
  zone_ec REAL,
  zone_ph REAL,
  zone_vpd REAL,
  zone_dli REAL,
  
  -- Metadata
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  engine_version TEXT DEFAULT 'v1.0-rules'
);

-- Track what grower actually planted (feedback loop)
CREATE TABLE IF NOT EXISTS planting_decisions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  recommendation_id INTEGER REFERENCES planting_recommendations(id),
  farm_id TEXT NOT NULL,
  group_id TEXT NOT NULL,
  
  -- What was actually done
  action TEXT NOT NULL, -- 'accepted', 'rejected', 'modified', 'skipped'
  actual_crop TEXT,     -- What was actually planted
  actual_date DATE,
  
  -- Grower's reasoning (optional)
  reason TEXT,
  override_score REAL,  -- If modified, what would score have been?
  
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Track crop performance (for future ML training)
CREATE TABLE IF NOT EXISTS crop_performance (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  farm_id TEXT NOT NULL,
  group_id TEXT NOT NULL,
  crop_id TEXT NOT NULL,
  
  -- Actual results
  seed_date DATE,
  harvest_date DATE,
  actual_duration_days INTEGER,
  yield_oz REAL,
  
  -- Environmental averages during grow
  avg_ec REAL,
  avg_ph REAL,
  avg_vpd REAL,
  avg_dli REAL,
  
  -- Quality metrics
  disease_incidents INTEGER DEFAULT 0,
  quality_rating INTEGER, -- 1-5 scale
  
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for query performance
CREATE INDEX IF NOT EXISTS idx_recommendations_farm ON planting_recommendations(farm_id, created_at);
CREATE INDEX IF NOT EXISTS idx_recommendations_group ON planting_recommendations(group_id, created_at);
CREATE INDEX IF NOT EXISTS idx_decisions_farm ON planting_decisions(farm_id, created_at);
CREATE INDEX IF NOT EXISTS idx_decisions_recommendation ON planting_decisions(recommendation_id);
CREATE INDEX IF NOT EXISTS idx_performance_farm ON crop_performance(farm_id, crop_id);
CREATE INDEX IF NOT EXISTS idx_performance_crop ON crop_performance(crop_id, harvest_date);

-- Sample analytics queries

-- Acceptance rate by farm
-- SELECT 
--   farm_id,
--   COUNT(*) as total_recommendations,
--   SUM(CASE WHEN action = 'accepted' THEN 1 ELSE 0 END) as accepted,
--   ROUND(100.0 * SUM(CASE WHEN action = 'accepted' THEN 1 ELSE 0 END) / COUNT(*), 2) as acceptance_rate_pct
-- FROM planting_recommendations r
-- LEFT JOIN planting_decisions d ON r.id = d.recommendation_id
-- WHERE r.created_at > date('now', '-30 days')
-- GROUP BY farm_id;

-- Most frequently overridden crops (what system recommends but growers reject)
-- SELECT 
--   recommended_crop,
--   COUNT(*) as times_recommended,
--   SUM(CASE WHEN d.action != 'accepted' THEN 1 ELSE 0 END) as times_rejected,
--   ROUND(100.0 * SUM(CASE WHEN d.action != 'accepted' THEN 1 ELSE 0 END) / COUNT(*), 2) as rejection_rate
-- FROM planting_recommendations r
-- LEFT JOIN planting_decisions d ON r.id = d.recommendation_id
-- WHERE r.created_at > date('now', '-60 days')
-- GROUP BY recommended_crop
-- HAVING times_recommended > 5
-- ORDER BY rejection_rate DESC;

-- Average score of accepted vs rejected recommendations
-- SELECT 
--   d.action,
--   COUNT(*) as count,
--   ROUND(AVG(r.score_overall), 2) as avg_score,
--   ROUND(AVG(r.confidence), 3) as avg_confidence
-- FROM planting_recommendations r
-- JOIN planting_decisions d ON r.id = d.recommendation_id
-- GROUP BY d.action;
