/**
 * Text-to-Speech route for Light Engine Foxtrot.
 * POST /api/tts { text, voice? }
 * Returns audio/mpeg generated by OpenAI.
 *
 * Farm identity is read from optional Authorization header or x-farm-id header.
 * Usage is logged per farm for cost attribution.
 */

import { Router } from 'express';
import OpenAI from 'openai';

const router = Router();

let openai = null;
try {
  if (process.env.OPENAI_API_KEY) {
    openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });
  }
} catch (e) {
  console.warn('[TTS] Failed to initialize OpenAI client:', e.message);
}

const ALLOWED_VOICES = new Set([
  'alloy',
  'ash',
  'ballad',
  'coral',
  'echo',
  'fable',
  'nova',
  'onyx',
  'sage',
  'shimmer',
  'verse',
]);

const DEFAULT_VOICE = process.env.ASSISTANT_TTS_VOICE || 'ash';
const DEFAULT_MODEL = process.env.ASSISTANT_TTS_MODEL || 'tts-1-hd';
const MAX_TEXT_LENGTH = 2000;

// Simple per-IP limiter: 20 requests/minute.
const requestHits = new Map();
const RATE_WINDOW_MS = 60_000;
const RATE_MAX = 20;
setInterval(() => requestHits.clear(), RATE_WINDOW_MS);

/** Extract farm_id from JWT Bearer token without blocking unauthenticated requests. */
function extractFarmId(req) {
  // Explicit header takes priority
  const headerFarmId = req.headers['x-farm-id'];
  if (headerFarmId) return headerFarmId;
  // Try JWT if present
  try {
    const auth = req.headers.authorization;
    if (auth && auth.startsWith('Bearer ')) {
      const payload = JSON.parse(Buffer.from(auth.split('.')[1], 'base64').toString());
      return payload.farm_id || null;
    }
  } catch { /* ignore malformed tokens */ }
  return process.env.FARM_ID || null;
}

/** tts-1: $15/1M chars, tts-1-hd: $30/1M chars */
function estimateTtsCost(model, charCount) {
  const perChar = model === 'tts-1' ? 0.000015 : 0.00003;
  return charCount * perChar;
}

router.post('/', async (req, res) => {
  const ip = req.ip || req.connection?.remoteAddress || 'unknown';
  const count = (requestHits.get(ip) || 0) + 1;
  requestHits.set(ip, count);

  if (count > RATE_MAX) {
    return res.status(429).json({ error: 'Too many TTS requests. Try again shortly.' });
  }

  if (!openai) {
    return res.status(503).json({ error: 'TTS unavailable. OPENAI_API_KEY is not configured.' });
  }

  const { text, voice = DEFAULT_VOICE } = req.body || {};

  if (!text || typeof text !== 'string' || text.trim().length === 0) {
    return res.status(400).json({ error: 'text is required' });
  }

  if (text.length > MAX_TEXT_LENGTH) {
    return res.status(400).json({ error: `text must be ${MAX_TEXT_LENGTH} characters or fewer` });
  }

  const selectedVoice = ALLOWED_VOICES.has(voice) ? voice : DEFAULT_VOICE;
  const farmId = extractFarmId(req);
  const charCount = text.trim().length;

  try {
    const response = await openai.audio.speech.create({
      model: DEFAULT_MODEL,
      voice: selectedVoice,
      input: text.trim(),
      response_format: 'mp3',
    });

    const buffer = Buffer.from(await response.arrayBuffer());

    console.log('[TTS] usage farm=%s model=%s chars=%d cost=$%s',
      farmId || 'unknown', DEFAULT_MODEL, charCount, estimateTtsCost(DEFAULT_MODEL, charCount).toFixed(6));

    res.setHeader('Content-Type', 'audio/mpeg');
    res.setHeader('Cache-Control', 'no-store');
    res.send(buffer);
  } catch (err) {
    console.error('[TTS] OpenAI error:', err?.message || err);
    console.warn('[TTS] failed farm=%s model=%s chars=%d err=%s',
      farmId || 'unknown', DEFAULT_MODEL, charCount, err?.message);

    if (err?.status === 429) {
      return res.status(429).json({ error: 'TTS provider rate limit. Try again shortly.' });
    }

    return res.status(502).json({ error: 'TTS generation failed' });
  }
});

export default router;
