/**
 * Text-to-Speech route for Light Engine Foxtrot.
 * POST /api/tts { text, voice? }
 * Returns audio/mpeg generated by OpenAI.
 */

import { Router } from 'express';
import OpenAI from 'openai';

const router = Router();

let openai = null;
try {
  if (process.env.OPENAI_API_KEY) {
    openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });
  }
} catch (e) {
  console.warn('[TTS] Failed to initialize OpenAI client:', e.message);
}

const ALLOWED_VOICES = new Set([
  'alloy',
  'ash',
  'ballad',
  'coral',
  'echo',
  'fable',
  'nova',
  'onyx',
  'sage',
  'shimmer',
  'verse',
]);

const DEFAULT_VOICE = process.env.ASSISTANT_TTS_VOICE || 'ash';
const DEFAULT_MODEL = process.env.ASSISTANT_TTS_MODEL || 'tts-1-hd';
const MAX_TEXT_LENGTH = 2000;

// Simple per-IP limiter: 20 requests/minute.
const requestHits = new Map();
const RATE_WINDOW_MS = 60_000;
const RATE_MAX = 20;
setInterval(() => requestHits.clear(), RATE_WINDOW_MS);

router.post('/', async (req, res) => {
  const ip = req.ip || req.connection?.remoteAddress || 'unknown';
  const count = (requestHits.get(ip) || 0) + 1;
  requestHits.set(ip, count);

  if (count > RATE_MAX) {
    return res.status(429).json({ error: 'Too many TTS requests. Try again shortly.' });
  }

  if (!openai) {
    return res.status(503).json({ error: 'TTS unavailable. OPENAI_API_KEY is not configured.' });
  }

  const { text, voice = DEFAULT_VOICE } = req.body || {};

  if (!text || typeof text !== 'string' || text.trim().length === 0) {
    return res.status(400).json({ error: 'text is required' });
  }

  if (text.length > MAX_TEXT_LENGTH) {
    return res.status(400).json({ error: `text must be ${MAX_TEXT_LENGTH} characters or fewer` });
  }

  const selectedVoice = ALLOWED_VOICES.has(voice) ? voice : DEFAULT_VOICE;

  try {
    const response = await openai.audio.speech.create({
      model: DEFAULT_MODEL,
      voice: selectedVoice,
      input: text.trim(),
      response_format: 'mp3',
    });

    const buffer = Buffer.from(await response.arrayBuffer());

    res.setHeader('Content-Type', 'audio/mpeg');
    res.setHeader('Cache-Control', 'no-store');
    res.send(buffer);
  } catch (err) {
    console.error('[TTS] OpenAI error:', err?.message || err);

    if (err?.status === 429) {
      return res.status(429).json({ error: 'TTS provider rate limit. Try again shortly.' });
    }

    return res.status(502).json({ error: 'TTS generation failed' });
  }
});

export default router;
